name: swift-language-git ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: sccache swift-language-git
      uses: actions/cache@v2
      with:
        path: /home/runner/work/swift-aur/swift-aur/swift-language-git/src/sccache
        key: swift-language-git-sccache

    - name: Build swift-language-git AUR
      uses: soloturn/build-aur-action@0.0.2
      with:
        # AUR repository name to build
        repo-name: swift-language-git

    - name: Upload arch pkg
      uses: actions/upload-artifact@v2
      with:
        name: zipped-arch-package
        path: /home/runner/work/swift-aur/swift-aur/swift-language-git/*.zst


# vim:set ts=2 sw=2 et:
